import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        fg: "var(--fg)",
        accent: "var(--accent)",
        muted: "var(--muted)",
        surface: "var(--surface)",
        border: "var(--border)",
        input: "var(--input)",
        ring: "var(--ring)",
        background: "var(--background)",
        foreground: "var(--foreground)",
        primary: {
          DEFAULT: "var(--primary)",
          foreground: "var(--primary-foreground)",
        },
        secondary: {
          DEFAULT: "var(--secondary)",
          foreground: "var(--secondary-foreground)",
        },
        destructive: {
          DEFAULT: "var(--destructive)",
          foreground: "var(--destructive-foreground)",
        },
        card: {
          DEFAULT: "var(--card)",
          foreground: "var(--card-foreground)",
        },
        popover: {
          DEFAULT: "var(--popover)",
          foreground: "var(--popover-foreground)",
        },
        // Crystal Coast Luxury palette
        crystal: {
          whiteSand: "var(--white-sand)",
          oceanFoam: "var(--ocean-foam)",
          coastalMist: "var(--coastal-mist)",
          seaGlass: "var(--sea-glass)",
          coralBlush: "var(--coral-blush)",
          deepTide: "var(--deep-tide)",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      fontSize: {
        // Fluid typography scale
        'xs': ['var(--font-size-xs)', { lineHeight: 'var(--line-height-tight)' }],
        'sm': ['var(--font-size-sm)', { lineHeight: 'var(--line-height-snug)' }],
        'base': ['var(--font-size-base)', { lineHeight: 'var(--line-height-normal)' }],
        'lg': ['var(--font-size-lg)', { lineHeight: 'var(--line-height-relaxed)' }],
        'xl': ['var(--font-size-xl)', { lineHeight: 'var(--line-height-relaxed)' }],
        '2xl': ['var(--font-size-2xl)', { lineHeight: 'var(--line-height-tight)' }],
        '3xl': ['var(--font-size-3xl)', { lineHeight: 'var(--line-height-tight)' }],
        '4xl': ['var(--font-size-4xl)', { lineHeight: 'var(--line-height-tight)' }],
        '5xl': ['var(--font-size-5xl)', { lineHeight: 'var(--line-height-none)' }],
        '6xl': ['var(--font-size-6xl)', { lineHeight: 'var(--line-height-none)' }],
        '7xl': ['var(--font-size-7xl)', { lineHeight: 'var(--line-height-none)' }],
        '8xl': ['var(--font-size-8xl)', { lineHeight: 'var(--line-height-none)' }],
        '9xl': ['var(--font-size-9xl)', { lineHeight: 'var(--line-height-none)' }],
        // Fluid clamp-based typography for modern responsive design
        'fluid-xs': ['clamp(0.75rem, 0.7rem + 0.25vw, 1rem)', { lineHeight: 'var(--line-height-tight)' }],
        'fluid-sm': ['clamp(0.875rem, 0.8rem + 0.375vw, 1.125rem)', { lineHeight: 'var(--line-height-snug)' }],
        'fluid-base': ['clamp(1rem, 0.9rem + 0.5vw, 1.25rem)', { lineHeight: 'var(--line-height-normal)' }],
        'fluid-lg': ['clamp(1.125rem, 1rem + 0.625vw, 1.5rem)', { lineHeight: 'var(--line-height-relaxed)' }],
        'fluid-xl': ['clamp(1.25rem, 1.1rem + 0.75vw, 1.875rem)', { lineHeight: 'var(--line-height-relaxed)' }],
        'fluid-2xl': ['clamp(1.5rem, 1.3rem + 1vw, 2.25rem)', { lineHeight: 'var(--line-height-tight)' }],
        'fluid-3xl': ['clamp(1.875rem, 1.6rem + 1.375vw, 3rem)', { lineHeight: 'var(--line-height-tight)' }],
        'fluid-4xl': ['clamp(2.25rem, 1.9rem + 1.75vw, 3.75rem)', { lineHeight: 'var(--line-height-tight)' }],
        'fluid-5xl': ['clamp(3rem, 2.5rem + 2.5vw, 4.5rem)', { lineHeight: 'var(--line-height-none)' }],
        'fluid-6xl': ['clamp(3.75rem, 3rem + 3.75vw, 6rem)', { lineHeight: 'var(--line-height-none)' }],
        'fluid-7xl': ['clamp(4.5rem, 3.5rem + 5vw, 8rem)', { lineHeight: 'var(--line-height-none)' }],
        'fluid-8xl': ['clamp(6rem, 4.5rem + 7.5vw, 12rem)', { lineHeight: 'var(--line-height-none)' }],
        'fluid-9xl': ['clamp(8rem, 6rem + 10vw, 16rem)', { lineHeight: 'var(--line-height-none)' }],
      },
      fontFamily: {
        sans: ['Lato', 'Inter', 'system-ui', 'sans-serif'],
        display: ['Playfair Display', 'serif'],
        serif: ['Playfair Display', 'serif'],
        body: ['Lato', 'Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'Consolas', 'monospace'],
      },
      fontWeight: {
        thin: 'var(--font-weight-thin)',
        extralight: 'var(--font-weight-extralight)',
        light: 'var(--font-weight-light)',
        normal: 'var(--font-weight-normal)',
        medium: 'var(--font-weight-medium)',
        semibold: 'var(--font-weight-semibold)',
        bold: 'var(--font-weight-bold)',
        extrabold: 'var(--font-weight-extrabold)',
        black: 'var(--font-weight-black)',
      },
      spacing: {
        '1': 'var(--space-1)',
        '2': 'var(--space-2)',
        '3': 'var(--space-3)',
        '4': 'var(--space-4)',
        '5': 'var(--space-5)',
        '6': 'var(--space-6)',
        '8': 'var(--space-8)',
        '10': 'var(--space-10)',
        '12': 'var(--space-12)',
        '16': 'var(--space-16)',
        '20': 'var(--space-20)',
        '24': 'var(--space-24)',
        '32': 'var(--space-32)',
        '40': 'var(--space-40)',
        '48': 'var(--space-48)',
        '56': 'var(--space-56)',
        '64': 'var(--space-64)',
      },
      boxShadow: {
        'soft': 'var(--shadow-soft)',
        'md': 'var(--shadow-md)',
        'lg': 'var(--shadow-lg)',
        'xl': 'var(--shadow-xl)',
        '2xl': 'var(--shadow-2xl)',
        'lg-glow': 'var(--shadow-lg-glow)',
      },
      backgroundImage: {
        'gradient-1': 'var(--gradient-1)',
        'gradient-2': 'var(--gradient-2)',
        'gradient-3': 'var(--gradient-3)',
        'gradient-4': 'var(--gradient-4)',
        'gradient-5': 'var(--gradient-5)',
        'gradient-mesh': 'var(--gradient-mesh)',
        'mesh-gradient-1': 'var(--mesh-gradient-1)',
      },
      animation: {
        'float-slow': 'float 20s ease-in-out infinite',
        'float-medium': 'float 30s ease-in-out infinite',
        'float-fast': 'float 15s ease-in-out infinite',
        'blob-1': 'blob 7s infinite',
        'blob-2': 'blob 8s infinite',
        'blob-3': 'blob 9s infinite',
        'fade-in': 'fadeIn 0.5s ease-out',
        'fade-in-up': 'fadeInUp 0.5s ease-out',
        'scale-in': 'scaleIn 0.2s ease-out',
        'slide-in-right': 'slideInRight 0.5s ease-out',
        'slide-in-left': 'slideInLeft 0.5s ease-out',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0px) translateX(0px)' },
          '25%': { transform: 'translateY(-20px) translateX(10px)' },
          '50%': { transform: 'translateY(-10px) translateX(-15px)' },
          '75%': { transform: 'translateY(15px) translateX(5px)' },
        },
        blob: {
          '0%': { transform: 'translate(0px, 0px) scale(1)' },
          '33%': { transform: 'translate(30px, -50px) scale(1.1)' },
          '66%': { transform: 'translate(-20px, 20px) scale(0.9)' },
          '100%': { transform: 'translate(0px, 0px) scale(1)' },
        },
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        fadeInUp: {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        scaleIn: {
          '0%': { opacity: '0', transform: 'scale(0.9)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        slideInRight: {
          '0%': { opacity: '0', transform: 'translateX(20px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        slideInLeft: {
          '0%': { opacity: '0', transform: 'translateX(-20px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
      },
      backdropBlur: {
        xs: '2px',
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};

export default config; 